### ISSUE TITLE
How to add single artist playlist and tracks

### ISSUE THREAD

**Issue by ghost** [fearthedear/hearmusic#1]
Hello,

i would like to know how can i show only one artist tracks of my choice or set only his name.

Thank You

**Comment by fearthedear** [comment]
Hey absaras, this is non-active repository. The docs of the hearthis api is here: https://hearthis.at/api-v2/.  As mentioned there, to list only a specific address, use this request:
https://api-v2.hearthis.at/{{artist}}

Single Artist
Example query: https://api-v2.hearthis.at/shawne/
